behaviors:
  RocketLander:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 5096
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1e6
    time_horizon: 64
    summary_freq: 10


environment_parameters:
  target_size:
      curriculum:
          - name: FirstTarget
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.2
            value: 10.0
          - name: SecondTarget
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.4
              require_reset: false
            value: 8.0
          - name: ThirdTarget
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.6
              require_reset: false
            value: 6.0
          - name: FourthTarget
            value: 3.0
        