default_settings: null
behaviors:
  RocketLander:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 5096
      learning_rate: 0.00025
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_path: Unity_Compiled_Files\Rocket_Lander
  env_args: null
  base_port: 39344
  num_envs: 1
  seed: 0
engine_settings:
  width: 500
  height: 500
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: 2021.03.09_1306_RocketLander
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
debug: false
