default_settings: null
behaviors:
  RocketLander:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 5096
      learning_rate: 0.0005815430763706476
      beta: 0.009030963618391816
      epsilon: 0.365233138986928
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.8252373414619711
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 50000
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
    framework: pytorch
env_settings:
  env_path: Unity_Compiled_Files\Rocket_Lander
  env_args: null
  base_port: 45336
  num_envs: 1
  seed: 0
engine_settings:
  width: 500
  height: 500
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  target_size:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 0
          value: 11.0
      name: Lesson1
      completion_criteria:
        behavior: RocketLander
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.3
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 1
          value: 9.0
      name: Lesson2
      completion_criteria:
        behavior: RocketLander
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 2
          value: 7.0
      name: Lesson3
      completion_criteria:
        behavior: RocketLander
        measure: progress
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.7
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3
          value: 5.0
      name: Lesson_5
      completion_criteria: null
checkpoint_settings:
  run_id: 2021.03.09_1331_RocketLander
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: true
  inference: false
debug: false
