behaviors:
  RocketLander:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 5096
      learning_rate: 0.00025
      beta: 0.001
      epsilon: 0.4
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100000000.0
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000

environment_parameters:
  target_size:
      curriculum:
          - name: Lesson1
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.3
              
            value: 10.0
          - name: Lesson2
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.5
              require_reset: false
            value: 8.0
          - name: Lesson3
            completion_criteria:
              measure: progress
              behavior: RocketLander
              signal_smoothing: true
              min_lesson_length: 100
              threshold: 0.7
              require_reset: false
            value: 6.0
          - name: Lesson_5
            value: 3.0