wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      4: 3.8.3
      5: 0.10.19
      8:
      - 3
batch_size:
  desc: null
  value: 1024
gamma:
  desc: null
  value: 0.99
lambda:
  desc: null
  value: 0.95
learning_rate:
  desc: null
  value: 0
steps:
  desc: null
  value: 100000000.0
