wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.8.7
      5: 0.10.21
      8:
      - 3
      - 5
