wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.7
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.8.7
      5: 0.10.21
      8:
      - 3
      - 5
beta:
  desc: null
  value: 0.00238635656615909
epsilon:
  desc: null
  value: 0.4579491764606649
gamma:
  desc: null
  value: 0.9904239156634572
lambd:
  desc: null
  value: 0.99
lambda:
  desc: null
  value: 0.9206411492958049
learning_rate:
  desc: null
  value: 0.00012013861489770469
